### ISSUE TITLE
Technology Stack

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#1]
Let's discuss what basic technologies we want to use.

Who is familiar with Angular and/or React? Which one would you enjoy more for this project?

**Comment by sacdallago** [comment]
:+1: I like that you are using issues for this, big +

**Comment by yashha** [comment]
I'm currently getting into React so I would prefer this, but Angular would work too.
Both would get the job done.

**Comment by sacdallago** [comment]
As a personal suggestion: don't limit yourselves to plain node and packages: there are many very interesting frameworks based on javascript where you could also gain some real business-advantage over a developer that knows "only" node. Also think out of the box: maybe you could go for something more mobile-oriented?

Just putting two frameworks to make my point:     
- [Meteor](https://www.meteor.com/)
- [Ionic](http://ionicframework.com)

But if you want to go for pure node + packages it's fine as well, just throwing options here ;)

**Comment by yashha** [comment]
I like Meteor, its awesome. I would like to look into Ionic as well.
So we can definitely do that.

**Comment by yashha** [comment]
On Tuesday we talked about Ionic and Meteor.
We thought that we don't need to provide app's (Ionic), because the content of our app, will not change often, so there is no need to provide an app for it.
Meteor is also not needed, unless we need an User-Login functionality, which we can implement with node, too.

We could just go for an Webpack/Grunt, Angular/React/Backbone.

As decided today:
Which of angular, react, backbone, we will decide after each of the members of team 9 has done his research on them.
There will be a meeting on Monday at 6:30 pm.
It would be good if members of project D would be there and some of group 8.
Otherwise we will decide what to use.

**Comment by sacdallago** [comment]
@yashha if you have specific questions for me or the mentors please @ me! Otherwise I will go on :dancer: and forget about answering :smile: (yes, they got inspired by my moves to draw :dancer: ). But I guess you just wanted to report what you did until now: nice, I appreciate that.  
You are totally free to chose whatever javascript-based technology you want! :) But **less research, more code**! Trust me on this: the best research is the implementation, and you have branches, so you can test out things ;) Also to show them to other team members.
**E** is gonna bundle things together for you, so you might also want to align with them.

:v:
