### ISSUE TITLE
Show loading animation until characters loaded

### ISSUE THREAD

**Issue by TheZoker** [Rostlab/JS16_ProjectF#100]
On the [characters page](https://got-stats.herokuapp.com/#/characters) it takes some time for the characters to show. So until this is done, there should be a loading animation, which tells people (especially with slow internet), that there is still something loading.

Good animations can be generated [here](http://loading.io/) or samples can be found [here](http://preloaders.net/en/circular)

One of my favirote, is this complete css made animation [here](http://codepen.io/jczimm/pen/vEBpoL)

Of course a GoT design like loader would be best

**Comment by sacdallago** [comment]
There's a discussion EVEN between me and @gyachdav .

Loading animations can be **SHIT** if you implement them obtrusively, but they can be made very nicely. Like: http://nanobar.micronube.com

But @gyachdav said no :( so, no?

**Comment by jorjo1** [comment]
#46

**Comment by gyachdav** [comment]
Why is loading 20 characters taking time? 

is this because the images are taking time to load? put a place holder, set a promise to switch to the actual image once its there and you're done. 

Is this because you are loading char data from A for 20 characters? you should not be loading data for 20  characters, this is not needed. 

Since we're all professionals here, I want to understand if this animation is REALLY needed or just a hack.
