### ISSUE TITLE
Presenting PLODs

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#117]
Maybe this has been discussed in other issues but I couldn't find any ref. 
1. We need ideas on how to present PLODs. Whatever you suggest think intuitive, colorful, entertaining.
2. When presenting PLOD you should have some text (either on the page or in a pop hint) that explains that predictions are based on data from the books *_and not the show *_. then make a reference to the description of the relevant prediction method (will be supplied by the B groups).

**Comment by sacdallago** [comment]
https://github.com/Rostlab/JS16_ProjectB_Group7/issues/5

**Comment by gyachdav** [comment]
Status? only 3 days overdue :laughing:

**Comment by goldbergtatyana** [comment]
It is not quite clear to me (I asked again) what the final model of Group 7 is. Comparing the results of all candidate models of Group 7 to the final model of Group 6, the model of Group 6 is the winning one!

So, as discussed on Monday in the call, we should use PLOD scores of Group 6 on characters' pages. Note, instead of showing 54.3% of death, it is better to show rounded numbers --> 54%.

I really like the text "Check out what our two different algorithms say" and "XXX likeliyhood to die is 50%". Btw, typo in "likeliyhood ", please change to "likelihood".

Below of this result, I suggest to add a description of what users see and this can look like this:
We developed a machine learning-based algorithm that predicts character's percentage likelihood of death (PLOD) based on characteristics such as age, gender, title and others (described here). 
Interested in the PLOD score of our slighlty less accurate predictor (described here)? If so, click me!

**Comment by mammuth** [comment]
Related #178

**Comment by mammuth** [comment]
<img width="747" alt="screen shot 2016-03-31 at 20 03 55" src="https://cloud.githubusercontent.com/assets/3121306/14185832/d3a3c4d2-f77b-11e5-9c77-4f5f6f14e5fc.png">

We could present groups 6 plod with the fancy progressbar, and below add the second prediction as text form?

@goldbergtatyana what are your suggestions what happens when someone clicks on _(described here)_?

**Comment by goldbergtatyana** [comment]
really like the visualization! I suggest that the "here" word will link to a new static page that will described the corresponding algorithm. I will provide these descriptions soon (latest by Saturday).

**Comment by mammuth** [comment]
:+1:
Alright, I will setup one page and create a markdown file that you can edit directly.
