### ISSUE TITLE
Twitter D4 Integration

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#118]
@CavidSalahov we have been told, you are responsible for integrating D4.
Could you please show us how to integrate the twitter sentiments of D4? 

(Integration of the other twitter group D5 is discussed in #31, current dev-status of both implementations is tracked in #101)

**Comment by jsalahov** [comment]
As pointed out by @julienschmidt see [here](https://github.com/Rostlab/JS16_ProjectD_Group4/issues/25#issuecomment-199776355)

**Comment by julienschmidt** [comment]
AFAIK no npm package exists yet. I'll implement mocks of those API functions later.

**Comment by jsalahov** [comment]
Package publishing is one command away, https://www.npmjs.com/package/gotsentimental
This one is old however

**Comment by julienschmidt** [comment]
Version 0.0.2 has an early version of the API (no CSV yet). I'll update the README and publish an example later.

**Comment by julienschmidt** [comment]
You can find our example app (which we use for testing & dev) here: https://github.com/Rostlab/JS16_ProjectD_Group4/tree/develop/example/app

Doc in README and CSV generation still missing, otherwise the API should be more or less complete now.

**Comment by julienschmidt** [comment]
Documentation is ready: https://github.com/Rostlab/JS16_ProjectD_Group4#usage

Please let us know in case you find any problems or miss some feature.

**Comment by yashha** [comment]
@julienschmidt 
Is this just demo data?
All three functions outputs the same
mostPopular, mostHated,mostDiscussed

**Comment by julienschmidt** [comment]
That's because all values are still `0`. Expect the missing code for the actual analysis tomorrow or even later today.

**Comment by yashha** [comment]
Routes:
`/d4/csv/:slug.csv`
`/d4/chart.css`
`/d4/chart.js`

`/d4/sentiment/top?number=4`
`/d4/sentiment/worst?number=4`
`/d4/sentiment/discussed?number=4`

`/d4/character/:id` e.g. 56ea4cfe8c27d7c637505648

**Comment by yashha** [comment]
Server part done, dummy data is provided
closed in favor of #139

**Comment by julienschmidt** [comment]
Our API is now final and should soon be available in [v0.2.0](https://github.com/Rostlab/JS16_ProjectD_Group4/releases/tag/v0.2.0)

Your implementation should mostly look like our example app: https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/example/app/app.js

Please notice that `gotsent.css` and `gotsent.js` do not provide an HTTP handler anymore, since it was just a dirty hack during our development which shouldn't be used in production. Express and the `sendFile` method should be used instead: https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/example/app/app.js#L50

Also we now provide an [`updateLoop`](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/example/app/app.js#L16) which updates the DB and crawls for new Tweets automatically in the background. The interval is configurable in the config.
