### ISSUE TITLE
Character listing

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#148]
I'm still confused as to why this page needs a loader or why rendering a table with the names and place holders for images takes longs. please explain and/or better yet come up with a way to optimize loading of this page.

**Comment by yashha** [comment]
The thing because there is a loader is that the images are not lazily loaded into the page, so it doesn't render the list component before the images has been loaded.
Your right it's improvable

**Comment by gyachdav** [comment]
see suggestion how to improve here #100

**Comment by sacdallago** [comment]
Well. Lazy loading **is** the way to solve this, @yashha already knows the solution :) And I discussed this in some issue in the past also.
Would be nice if someone could take care of improving this, someone != @yashha or @jorjo1 :D

**Comment by mammuth** [comment]
It doesn't look like the long delay is due to the loading of the images. I think on the first opening of the characters page the client requests the server to load all characters from A's database, then the server gives the client the first 20 to render. ( @mina-zaki might complain here, if that's not correct, please :wink: ).

So there are two solutions:
- A implements something like an offset / pagination to the request of characters
- our server-component can easily cache the characters pretty long, since they don't change that often.

The 2nd solution should be implemented, and if someone feels like he has too much time, the first one might be cool aswell.

**Comment by yashha** [comment]
Closed in favor of #159
