### ISSUE TITLE
Map on dev server still looks funny on mobile. 

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#166]

**Comment by mammuth** [comment]
There is an issue in the map repo for that. 

I reverted the commit that did some optimizations for the map on mobile because the map-guys did some more advanced stuff. Probably they didn't yet published it when we delayed yesterday evening. 

So probably the "funnyness" is going to resolved in future gotmap versions.

**Comment by gyachdav** [comment]
Cool please reference the issue here so we won't forget about it. Thanks.

**Comment by mammuth** [comment]
Was on mobile before, otherwise I had linked the issue. :+1:

https://github.com/Rostlab/JS16_ProjectC_Group10/issues/181

**Comment by mammuth** [comment]
As discussed in the other issue, the responsiveness won't be included in the map-package itself. I'm on it to add it to our map-component.
