### ISSUE TITLE
Suspicious requests

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#198]
Hey guys. Looking at the server logs (of the api) I see a bunch of:

``` bash
[Wed Mar 30 2016 00:01:50] [LOG]   [Worker 4] Request incoming: /sentiment/find
[Wed Mar 30 2016 00:01:50] [LOG]   [Worker 4] 401 - no token sent
```

Between 21:47 and 1:50. I don't know if this was you, the twitter groups, or someone else. I just wanted to report, in case you were having some issues or spontaneous exceptions in your code, this might be the reason!

**Comment by sacdallago** [comment]
I'm still getting a lot of these right now:

``` bash
[Wed Mar 30 2016 10:25:37] [LOG]   [Worker 7] Request incoming: /sentiment/find
[Wed Mar 30 2016 10:25:37] [LOG]   [Worker 7] 401 - no token sent
```

If you are working on this, please let me now ASAP so we can pinpoint the problem

**Comment by yashha** [comment]
The error comes probably from one of the sentiments packages, because I don't provide a token, but I think I think there is another bug
Locally when I deploy and set the env variables the urls are correct, on heroku the urls are https://got-stats.herokuapp.com/NaNcharacters
So there is still a problem with those

**Comment by sacdallago** [comment]
I think I have this sorted out, thanks @yashha
