### ISSUE TITLE
Deployment / Live-Testing

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#2]
Any favors on where to host it? If not I could host it on a vServer of mine and add a webhook so that the masterbranch automagically gets deployed? 

Not that important until we have some stuff we want to test non-locally or show our process to other groups easily.

**Comment by yashha** [comment]
> vServer of mine

Sounds good. That would be awesome. 
I suppose, we get an server from the seminar at some point.
@sacdallago Can you tell us something about the server we will be using, when we will get access to it?

**Comment by sacdallago** [comment]
@yashha @mammuth sorry guys but hosting a VM at the Lab is not possible. You might want to look at AWS, Heroku or google cloud platform ;)

**Comment by yashha** [comment]
I saw the suggestions  on heroku and AWS on rostlabs wiki some minutes ago, too.
What do you guys think about getting an AWS NoSQL DB and deploying on heroku.

**Comment by yashha** [comment]
In free version:
Heroku: Apps sleep after 30min of inactivity, but doesn't expire ever
AWS EC2: Expires after 12 months
Google CS App Engine: Doesn't expire

https://www.heroku.com/pricing
https://aws.amazon.com/free/
https://cloud.google.com/appengine/ 

After relooking at them, I would try the Google CS App Engine.

**Comment by jorjo1** [comment]
I think I would go for AWS because of bandwidth reasons. Except for the case we are not going to need much?

**Comment by yashha** [comment]
You are right, that's probably the way to go.
The thing is it expires in 12 months, so if we want to keep the app online after 12 month we need somebody to recreate an account or we think about getting money through some platform to keep it online. Maybe its not important to keep it up, but I wanted to mention it.

**Comment by yashha** [comment]
Until Mondax
- [x] Create Email Account -> jsseminar@tuta.io
- [ ]  Create AWS Acount

**Comment by yashha** [comment]
I created an email account, but I have a problem know.
On which name the server should run, Amazon needs name, address, phone number AND a credit card.

**Comment by jorjo1** [comment]
Hi guys, 

since there are details we cannot and should not share on github (like hosting email/pw), I propose that we discuss this on the Signal group. (https://whispersystems.org/). You can find further informations in the google groups (8 and 9).

**Hosting**
I don't have a credit card so I cannot contribute to the registration of the Amazon account. If noone can sign up for the service, we should probably think about using Google.

**Mockup**
I will try to apply the information from the other projects and come up with an idea for the design and content of the web page in the next few days. If you have an idea, don't hesitate to share it!

**Comment by yashha** [comment]
Google needs bank details, too. But instead of just credit cards, it takes also ordinary bank accounts.

**Comment by yashha** [comment]
So ...
Google just gives only 60 days trial.

AWS would be pretty good I think.
Does somebody know the education program of Amazon?
https://aws.amazon.com/education/awseducate/
We would need somebody to provide his credit card.

Otherwise we should just use heroku. It needs nothing.
We will first of all a platform which has to sleep 6h a day and sleeps after 30 min of inactivity.
We can easily upgrade to better tiers, and get an Euro from everybody at one of the presentation dates.

**Comment by mina-kleid** [comment]
If the purpose of the project is just the seminar i dont see any issue with sleeping after inactivity. Otherwise if the purpose is having a live platform, then the people of the seminar should provide us with a robust stack that doesnt sleep or at least a credit card to use for a good system.

**Comment by mammuth** [comment]
I agree with mina-zaki. 

If we need to host on a long-term view with the possibility to scale Rostlab might provide an infrastructure.
Until that we can just start developing locally and if we want to share something with other teams we can deploy it an cheap vServer of anyone.

**Comment by yashha** [comment]
Or we just use heroku.

**Comment by gyachdav** [comment]
We're working on a solution for you. Please proceed with developing locally for now. This will be resolved during presentation week.
