### ISSUE TITLE
Cookie monster

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#212]
According to the "new" law on cookies from the EU, users have to be informed if anything of their session gets stored when they visit the page.
For example, if you cache in localStorage like I suggested yesterday, you need to put a [cookie consent](https://silktide.com/tools/cookie-consent/)

**Comment by mammuth** [comment]
For your stated use case that's not correct imho, because such a hint is only for person related data (as stated in the sites privacy policy) :wink: 
But since we're using Google analytics such a hint would be necessary. 

Actually we would need to wait until the user acknowledges the privacy policy (which we don't have, atm, but would be much more important than those EU-Cookie-Hints), before we can initialize analytics. 

But we should keep it simple, right now that's no law but only a directive. 
Afaik for users from Austria that's already enforced. 

There are even more things todo if you want to be more or less law-conform. For example you need to make person related informations that are used in analytics anonymous for users from certain countries...

**Comment by mammuth** [comment]
What I primarily want to say:
We probably don't have anyone with good knowledge in these law-related stuff, so keep it simple or find someone who is able to tell us how to properly do everything...

**Comment by gyachdav** [comment]
Privacy policy text in HTML format attached. 

[privacypolicy.txt](https://github.com/Rostlab/JS16_ProjectF/files/200346/privacypolicy.txt)
