### ISSUE TITLE
Contribute page

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#228]
- [x] Write some text
- [x] API links
- [x] NPM packages
- [x] GitHub Repo 
- [x] Community (editing the path)

**Comment by jorjo1** [comment]
We should remove this from the main navigation in the header, it's not what excites the users and such information is usually found in the footer of the page. There are `contribute` and `about` pages in the navi, so I would remove `contribute`.

**Comment by gyachdav** [comment]
fine just make sure it is in the footer. This link should forward to the map editor. @sacdallago what is the url for the map editor?

**Comment by sacdallago** [comment]
URL? I thought it would be integrated somewhere in F!

We can always make it run in some subdomain, like http://edit.got.show

**Comment by sacdallago** [comment]
I mean the http://map.got.show already exists and probably it would make more sense to put the editor there? I like that subdomain

**Comment by gyachdav** [comment]
yup agreed. @jorjo1 please forward to http://map.got.show when Contribute is clicked.

**Comment by gyachdav** [comment]
Status?

**Comment by Andrew094** [comment]
I don't know what you expect for the bullet points community and NPM packages

**Comment by goldbergtatyana** [comment]
Since I dont see a link to the markdown file for the developers description, here comes Dmitrii's text for it with my minor modifications:

WHAT IT IS

A song of Ice and Fire provides statistical information about the GoT
world and the impact it has on ours. Should we be worried about Sansa Stark?
Where exactly has Jon Snow travelled? And how many tweets were written about Hound?

HOW IT STARTED

Being huge machine learning nerds at TU Munich’s chair of Bioinformatics and GoT fans,
we wanted to use our data-crunching skills to get new insights into our beloved series (world?).
We also had to prepare material for a JavaScript seminar that we run each semester. Long story short, we decided to let our students build this web service, improving their knowledge of JavaScript in the process!

DIVIDING TEAMS

We wanted to have in-depth description of characters, trace their travels on the map, see what other fans felt about them, and compute how much danger characters are in. So, we divided our students into several teams: 2 teams used machine learning approaches to calculate Likelihood of Death for each character, 2 teams used sentiment analysis of tweets to deduce how fans feel about GoT characters and 1 team plotted charachters' footsteps on the GoT map using data mining.

We also had 2 teams who were in charge of continuous integration of individual projects and 2 teams who assembled everything into this awesome [got.show](got.show) app.

OPEN SOURCE & OPEN DATA PROJECT

Our results amused and pleased us, so we decided to share our findings with the fandom!
Now it's your turn - use the data we made available and build beautiful useful apps about the GoT world!
