### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectF#235]
@mammuth assigning to you to give initial guidance for draft. feel free to delegate
- [x] Rotating content: 2 characters faceoff (Arya vs Cersei, find out who are the main antagonists) have stats as on a ranking page (PLOD (with explanation), Sentiments) and one map under opposite images. 
- [x] Allocate a place holder for a block of text that will show the first paragraph from landing pages. The idea here is to show a few sentences from each published landing page. the result would look the home page of a blog.

**Comment by mammuth** [comment]
There is a WIP-PR here: https://github.com/Rostlab/JS16_ProjectF/pull/236

To be clear:
For your second point we would add a placeholder that is filled by a markdown-file. 
Since we said the landing pages will be static html there is no easy way to integrate the first paragraph of the landing pages automatically on the homepage.

**Comment by mammuth** [comment]
Closing in favor of the more specific issues...
