### ISSUE TITLE
Character-Detail: PLOD of 100% if character is dead

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectF#276]
_If a character has a date of death, then the PLOD should always be 100% and his thomb stone should be red and the menu bar will have the word D E A D throughout the whole bar on it_

**Comment by sacdallago** [comment]
This is an interesting case:
https://got-stats.herokuapp.com/characters/Stannis%20Baratheon

Look at the map! It has a place of death... @mbandle @AlexBeischl @tPiffrader you manually generate that data, right? Is there someplace/api call that this data can be `GET` so that we can have consistency in the frontend page, aka: showing that a character is not 93% likely to die, but 100% dead :D
