### ISSUE TITLE
Update to react 15

### ISSUE THREAD

**Issue by TheZoker** [Rostlab/JS16_ProjectF#343]
https://facebook.github.io/react/blog/2016/04/07/react-v15.html

Latest version is: v15.0.1

**Comment by mammuth** [comment]
What are advantages of the releases between? 
It's one day before our release, if there isn't something crucial, those updates are nothing that need to be done...

**Comment by TheZoker** [comment]
I guess mainly its good to keep everything up2date, because there are always many bug fixes in such a main release. They also improved svg handling.

**Comment by mammuth** [comment]
I don't think the same way :wink:
Generally, blindly upgrading major versions because "hey, there's an update" isn't anything that suits the development of applications with various components and dependencies... 
Sure, this site is small and probably there aren't any fancy deps, but we started with a certain version and the whole development is based on that. 

Furthermore we have other stuff to do than controlling whether everything is working fine after an upgrade. 
If there are no good reasons for upgrading, I'd stay with the stable version we're using. 

@yashha, wanna decide here?

**Comment by TheZoker** [comment]
That's why I did not update it directly, but opened an issue ;)
Facebook says:

> If your code is free of warnings when running under React 0.14, upgrading should be easy.
> The bulk of changes in this release are actually behind the scenes, impacting the way that React interacts with the DOM. The other substantial change is that React now supports the full range of SVG elements and attributes. Beyond that we have a large number of incremental improvements and additional warnings aimed to aid developers. We’ve also laid some groundwork in the core to bring you some new capabilities in future releases.

And I don't say that you have to give this a high prio, but keep it in mind, if the all main things are done. The issue system is not only for short term issues, but also for long term, that need some time and investigation.

**Comment by yashha** [comment]
Well it won't change much, I see the dom output is cleaner after the update, but it's really not much.
If you want to update it and test it in a separate branch you can do it, but there is no need in doing it.

**Comment by sacdallago** [comment]
Right before my bachelor defense the highly unstable (not 1.x) version of the node framework I was using decided to have its 0.8 to 0.9 bump... Destroying yet no core-functionalities, but the dependencies (aka: components I was using bound to that framework).

From my side: just be careful if you use react-bound dependencies (stuff in you package.json that has the name "react" somewhere in it :D :D )
