### ISSUE TITLE
Integration of projects B,C,D

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectF#5]
Hello guys, 

I'm Alex from Project E. And I am responsible for delivering ProjectsC from Group 10 and Project B from Group7 to you.

As written [here](https://groups.google.com/forum/#!topic/javascript-technology-2016/dR1IJlAJN6M) we (Project E team) need to publish the projects to NPM, so you can upload them.

Also according to [wiki](https://rostlab.org/owiki/index.php/Javascript_technology_2016#Project_F) you need to 

> Create the menus that will load the apps created in projects B-D

So, if I understood correctly, the output of projects B-D will be web pages that you need to show in your web site.

Do you have any ideas about how you will show 6 different solutions in your app?
And how npm packages should be structured to make the integration easier?

**Comment by mammuth** [comment]
So we have two things when we speak about _integration_ I guess:
1. Installation / making the package available in our app
2. Integration of an actual component in certain pages of our app

The first one can be done by packaging the project apps as npm modules. 

For integrating the actual project-app with their frontend (2) in our pages there might be a couple of options I can think of:
1. Requireing modules via Browserify/Webpack
2. [ES6 Modules](http://www.2ality.com/2014/09/es6-modules-final.html)
3. [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM)

Are my assumptions correct? Do you think of other options, @yashha ?

**Comment by yashha** [comment]
I don't have more ideas.
I think their enough. ;)
I only know about es6 modules yet.
The rest wouldn't be a problem i'm sure you can read easily into that.

**Comment by AlexMoroz** [comment]
Browserify/Webpack/ES6 Modules won't work, coz we need to integrate front-end also.
Shadow DOM looks possible, but I can't see any difference between it and iframe. And iframe seems shitty solution.

**Comment by mammuth** [comment]
Isn't it possible to export a function in the ES6 modules, that on call, render the frontend in the DOM-parent?
@sacdallago do you have any suggestions or experience in how to handle this?

**Comment by sacdallago** [comment]
Well, commonly speaking frontend logic and frontend representation are separated when it comes to these kind of libraries. For example: projects B have to render a PLOD which is just a numerical value, but they can nicely separate the logic of the calculation from an example implementation in, say, D3, and service this example also as part of the library via shadow DOM.
Examples of this are everywhere on the web, stupidly also UI frameworks such as bootstrap or semantic ui.
It's definetly harder to do this for project C10, because they have already put SO MUCH effort into their UI that it would be a shame to not use it and also it is not meant to be an example of the use of their logic, but the logic and the representation are interleaved and strongly coupled together.
Project **E** would need to come up with a way of having, for example, C10 integrated in the final website, so that it doesn't **feel** like they are two separate things, but that it's one continuous flow. This can be achieved for example by having a menu that renders on top of the view. The choice, though, is entirely up to you.

As to Browserify/Webpack/ES6, as @AlexMoroz says these concepts are not entirely relevant to the problem at hand. You have one layer to solve before going to that. But @AlexMoroz this should be up to your group, ask your teammates how you can do this? :) It's hard, I know, but this is the challenge for your team :)

Given all of the above, I think the choice can't be global, every _library_ needs to be thought trough singularly.

P.S.: sorry for coming back to you so late but I opened the notification and closed the window and puff, I forgot this existed :D thank good I double check everything because I know I'm :older_man: and forgetful :D :D

**Comment by AlexMoroz** [comment]
The only solution I have is to convert projects B,C,D to angular directives and services, so you can easily add them with require to your project. Is it possible in React?

**Comment by yashha** [comment]
@AlexMoroz I searched for ways to integrate angular into react, but there is no.
Because you have only one html file:
What you should do is packaging your Javascript up into one file. (Browsify, Webpack)
And expose us that Javascipt file and one packaged css file and a simple React component containing your html.

Any other solutions?

**Comment by AlexMoroz** [comment]
What do you mean by 

> React component containing your html

?
Any examples?

**Comment by yashha** [comment]
Something like this:
https://github.com/Rostlab/JS16_ProjectF/blob/develop/app/components/public/Start/Map/Map.jsx

**Comment by yashha** [comment]
Altenatively to brosify and webpakc, could you even expose a module using CommonJS.
http://requirejs.org/docs/commonjs.html#intro
At least I think it is possible :)

And we make an React component using your HTML, too. So you don't need to make a extra react component.

**Comment by yashha** [comment]
Ok angular, would work too ;)
I got it working.
http://codepen.io/anon/pen/ZWpaJV
I would recommend not going for angular though, its a big library, which it in this case not necessary for getting the result.
