### ISSUE TITLE
Api call for character

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectF#59]

**Comment by jorjo1** [comment]
@mina-zaki we need also getCharacters() with a possibility to return an array of GoT-characters according to a pagination.
For example: assume we display 20 profiles per page (n)
first page: 0-19 (n=0)
second page: 20-39 (n=1) 
and so on..
:eyes:

**Comment by sacdallago** [comment]
@jorjo1 already been discussed here https://github.com/Rostlab/JS16_ProjectA/issues/89

Btw I noticed that you are loading all char + their pictures when opening /characters (p.s.: the page is called `character` but the link is `characters`, stay consistent).
Are the calls to get the images and the data separate? Because if that is the case: first get the "soft data", then get the images. This way the rendering of the page should be faster + you just simply have to inject the image in the right place.

Last but not least: put a loader? It was you idea anyway @jorjo1 , right?

**Comment by jorjo1** [comment]
@sacdallago we have observed already that the page names may cause some problems, we are changing their names some time soon.

The `/characters` page you see loads all at once, but we did the pagination yesterday (and display only max. 20 characters per page), which makes it a lot faster to render. One problem we still have is that we get the whole JSON info at once (~600kb), instead of small chunks for the separate pages. We are still working on this issue. @yashha did I forget something?

Yes I am still putting the loader! As we have already discussed in #46, it will be a simple progress bar at the top of the page.

**Comment by gyachdav** [comment]
-1 for loader. 

@sacdallago I think it's time to open an issue describing what goes in the character portal page. 

It should be (in my opinion):
1. a few blocks of top 5s. Top loved on Twitter top hated top survivors top most likely to die . Top popular (using the upcoming pageRank). 
2. A big autocomplete text box that allows you to search your favorite character. With advanced controls for sorting and filtering. 
3. Area for search results. 

Search results and top Xs list serve as gateways into individual characters pages. 

Thoughts?

**Comment by jorjo1** [comment]
Thank you for the feedback. Ok, no loading bar.

We are filtering and sorting the character-list in #78, a search field is to be added.
Results are also to be shown dynamically.

Furthermore (Ranking page): 
- I am doing a field with the two most controversial characters ( 1 vs. 1 ) which data comes from PLOD.
